Repository Gongju-Unity-Bootcamp/Project.998S, pull requests merged in 2024-02, with the labels that each got.

#19 [Refactor] 애니메이션 클립 추가
  Project.998S/Assets/Downloads/Animated Fantasy Polygon Chest/Animated Fantasy Polygon Chest.unitypackage.meta
  Project.998S/Assets/Downloads/LowPolyFoodLite/LowPolyFoodLite_2020.3.0_URP_v1.0.unitypackage.meta
  Project.998S/Assets/Downloads/LowPolyRPGWeapons_Lite/LowPolyRPGWeaponsLite_2020.3.0_HDRP_v1.0.unitypackage.meta
  Project.998S/Assets/Downloads/LowPolyRPGWeapons_Lite/LowPolyRPGWeaponsLite_2020.3.0_URP_v1.0.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Characters/SRP/PT_Armors_Free_URP_12.1.10.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Characters/SRP/PT_Doctor_URP_10.10.1.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Characters/SRP/PT_Doctor_URP_12.1.10.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Characters/SRP/PT_Peasants_Free_URP_10.10.1.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Characters/SRP/PT_Peasants_Free_URP_12.1.10.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Characters/SRP/PT_Priest_URP_10.10.1.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Characters/SRP/PT_Priest_URP_12.1.10.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Characters/SRP/PT_Skeleton_URP_10.10.1.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Characters/SRP/PT_Skeleton_URP_12.1.10.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Demos/Peasants_Free_Asset/Free_Character_Demo.unity
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Demos/Peasants_Free_Asset/Prefabs/PT_Hayfork_011.prefab
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Environments/SRP/PT_Environment_Pack_URP_10.10.1.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Environments/SRP/PT_Environment_Pack_URP_7.5.3.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Environments/SRP/PT_Nature_Free_URP_10.10.1.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Environments/SRP/PT_Nature_Free_URP_12.1.10.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Weapons/SRP/PT_Lowpoly_Weapons_URP.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Weapons/SRP/PT_Weapons_URP_10.10.1.unitypackage.meta
  Project.998S/Assets/Downloads/Polytope Studio/Lowpoly_Weapons/SRP/PT_Weapons_URP_12.1.10.unitypackage.meta
  Project.998S/Assets/Resources/Animations.meta
  Project.998S/Assets/Resources/Animations/0.Ground_Idle_.fbx
  Project.998S/Assets/Resources/Animations/0.Ground_Idle_.fbx.meta
  Project.998S/Assets/Resources/Animations/0.HandsUp.fbx
  Project.998S/Assets/Resources/Animations/0.HandsUp.fbx.meta
  Project.998S/Assets/Resources/Animations/0.Right_Hand_Idle_.fbx
  Project.998S/Assets/Resources/Animations/0.Right_Hand_Idle_.fbx.meta
  Project.998S/Assets/Resources/Animations/0.RunAway.fbx
  Project.998S/Assets/Resources/Animations/0.RunAway.fbx.meta
  Project.998S/Assets/Resources/Animations/0.TakeDown.fbx
  Project.998S/Assets/Resources/Animations/0.TakeDown.fbx.meta
  Project.998S/Assets/Resources/Animations/0.TestSlash.fbx
  Project.998S/Assets/Resources/Animations/0.TestSlash.fbx.meta
  Project.998S/Assets/Resources/Animations/0.WakeUp.fbx
  Project.998S/Assets/Resources/Animations/0.WakeUp.fbx.meta
  Project.998S/Assets/Resources/Animations/0.WakeUp1_.fbx
  Project.998S/Assets/Resources/Animations/0.WakeUp1_.fbx.meta
  Project.998S/Assets/Resources/Animations/Ground_Idle_falg_in.fbx
  Project.998S/Assets/Resources/Animations/Ground_Idle_falg_in.fbx.meta
  Project.998S/Assets/Resources/Animators.meta
  Project.998S/Assets/Resources/Animators/PT_Male_Peasant_01_Animator.controller
  Project.998S/Assets/Resources/Animators/PT_Male_Peasant_01_Animator.controller.meta
Labels: documentation

#75 [Feature] 턴 시스템 조사 및 구현
  Project.998S/Assets/Materials.meta
  Project.998S/Assets/Materials/Blue.mat
  Project.998S/Assets/Materials/Blue.mat.meta
  Project.998S/Assets/Materials/Red.mat
  Project.998S/Assets/Materials/Red.mat.meta
  Project.998S/Assets/Prefabs.meta
  Project.998S/Assets/Prefabs/Enemy.prefab
  Project.998S/Assets/Prefabs/Enemy.prefab.meta
  Project.998S/Assets/Prefabs/Player.prefab
  Project.998S/Assets/Prefabs/Player.prefab.meta
  Project.998S/Assets/Scenes/TrunSystem.unity
  Project.998S/Assets/Scenes/TrunSystem.unity.meta
  Project.998S/Assets/Scripts/BattleHUD.cs
  Project.998S/Assets/Scripts/BattleHUD.cs.meta
  Project.998S/Assets/Scripts/ButtonClick.cs
  Project.998S/Assets/Scripts/ButtonClick.cs.meta
  Project.998S/Assets/Scripts/GameManager.cs
  Project.998S/Assets/Scripts/GameManager.cs.meta
  Project.998S/Assets/Scripts/TurnSystem.cs
  Project.998S/Assets/Scripts/TurnSystem.cs.meta
  Project.998S/Assets/Scripts/Unit.cs
  Project.998S/Assets/Scripts/Unit.cs.meta
Labels: enhancement

#86 [Feature] 게임 매니저 구현
  Project.998S/Assets/Resources/Animators/enCockatriceA.controller
  Project.998S/Assets/Resources/Animators/enWolfA.controller
  Project.998S/Assets/Resources/Animators/enWolfB.controller
  Project.998S/Assets/Resources/Prefabs/enCockatriceA.prefab
  Project.998S/Assets/Resources/Prefabs/enWolfA.prefab
  Project.998S/Assets/Resources/Prefabs/enWolfB.prefab
  Project.998S/Assets/Scenes/Game.meta
  Project.998S/Assets/Scenes/Game.unity
  Project.998S/Assets/Scenes/Game.unity.meta
  Project.998S/Assets/Scenes/Game/998S Profile.asset
  Project.998S/Assets/Scenes/Game/998S Profile.asset.meta
  Project.998S/Assets/Scenes/Game/998S Settings.lightning.lighting
  Project.998S/Assets/Scenes/Game/998S Settings.lightning.lighting.meta
  Project.998S/Assets/Scenes/Game/LightingData.asset
  Project.998S/Assets/Scenes/Game/LightingData.asset.meta
  Project.998S/Assets/Scenes/Game/ReflectionProbe-0.exr
  Project.998S/Assets/Scenes/Game/ReflectionProbe-0.exr.meta
  Project.998S/Assets/Scenes/Stage.unity
  Project.998S/Assets/Scenes/TrunSystem.unity
  Project.998S/Assets/Scripts/Character/AnimatorParameter.meta
  Project.998S/Assets/Scripts/Character/AnimatorParameter/AnimatorParameter.cs
  Project.998S/Assets/Scripts/Character/AnimatorParameter/AnimatorParameter.cs.meta
  Project.998S/Assets/Scripts/Character/Character.cs
  Project.998S/Assets/Scripts/Character/Enemy.cs
  Project.998S/Assets/Scripts/Character/Player.cs
  Project.998S/Assets/Scripts/Data/CharacterData.cs
  Project.998S/Assets/Scripts/Item.meta
  Project.998S/Assets/Scripts/Item/Consump.meta
  Project.998S/Assets/Scripts/Item/Equip.meta
  Project.998S/Assets/Scripts/Manager/GameManager.cs
  Project.998S/Assets/Scripts/Manager/SpawnManager.cs
  Project.998S/Assets/Scripts/Manager/StageManager.cs
  Project.998S/Assets/Scripts/PlayerController.cs
  Project.998S/Assets/Scripts/UI.meta
  Project.998S/ProjectSettings/TagManager.asset
Labels: enhancement

#104 [Feature] 플레이어 턴과 몬스터 턴 구분
  Project.998S/Assets/Scripts/Character/Controller/Default/Controller.cs
  Project.998S/Assets/Scripts/Character/Controller/EnemyController.cs
  Project.998S/Assets/Scripts/Character/Controller/PlayerController.cs
  Project.998S/Assets/Scripts/Character/Default/Character.cs
  Project.998S/Assets/Scripts/Character/Enemy.cs
  Project.998S/Assets/Scripts/Manager/DataManager.cs
  Project.998S/Assets/Scripts/Manager/Default/Managers.cs
  Project.998S/Assets/Scripts/Manager/GameManager.cs
  Project.998S/Assets/Scripts/Manager/ResourceManager.cs
  Project.998S/Assets/Scripts/Manager/SoundManager.cs
  Project.998S/Assets/Scripts/Manager/SpawnManager.cs
  Project.998S/Assets/Scripts/Manager/StageManager.cs
  Project.998S/Assets/Scripts/Manager/UIManager.cs
  Project.998S/Assets/Scripts/UI/Default/UIPopup.cs
  Project.998S/Assets/Scripts/UI/Default/UISubItem.cs
  Project.998S/Assets/Scripts/UI/Default/UserInterface.cs
  Project.998S/Assets/Scripts/Util/Define.cs
  Project.998S/Assets/Scripts/Util/Extensions.cs
  Project.998S/Assets/Scripts/Util/UnityExtensions.cs
  Project.998S/Assets/Scripts/Util/Utils.cs
Labels: enhancement

#106 [Feature] 캐릭터 콘텐츠 일부 구현
  Project.998S/Assets/Resources/Animators/enArmoredWolf.controller
  Project.998S/Assets/Resources/Animators/enBee1.controller
  Project.998S/Assets/Resources/Animators/enCockatriceA.controller
  Project.998S/Assets/Resources/Animators/enWolfA.controller
  Project.998S/Assets/Resources/Animators/enWolfB.controller
  Project.998S/Assets/Scripts/Character/AnimatorParameter/AnimatorParameter.cs
  Project.998S/Assets/Scripts/Character/Controller/Default/Controller.cs
  Project.998S/Assets/Scripts/Character/Controller/EnemyController.cs
  Project.998S/Assets/Scripts/Character/Controller/PlayerController.cs
  Project.998S/Assets/Scripts/Character/Default/Character.cs
  Project.998S/Assets/Scripts/Manager/GameManager.cs
  Project.998S/Assets/Scripts/Manager/StageManager.cs
  Project.998S/Assets/Scripts/Util/Define.cs
  Project.998S/Assets/Scripts/Util/Extensions.cs
  Project.998S/Assets/Scripts/Util/Utils.cs
Labels: enhancement

#128 [Feature] Cinemachine 배치 및 파티클 제작
  Project.998S/Assets/Cinemachine.meta
  Project.998S/Assets/Resources/Prefabs/EndBattleCamera.prefab
  Project.998S/Assets/Resources/Prefabs/EndBattleCamera.prefab.meta
  Project.998S/Assets/Resources/Prefabs/HitParticle.prefab
  Project.998S/Assets/Resources/Prefabs/HitParticle.prefab.meta
  Project.998S/Assets/Resources/Prefabs/StageStartCamera.prefab
  Project.998S/Assets/Resources/Prefabs/StageStartCamera.prefab.meta
  Project.998S/Assets/Resources/Prefabs/TurnCamera.prefab
  Project.998S/Assets/Resources/Prefabs/TurnCamera.prefab.meta
  Project.998S/Assets/Scenes/Game.unity
Labels: enhancement

#142 [Chore] UI 배치 및 파일 수정
  Project.998S/Assets/HanWooJeong/Inventory/InventoryItem.png
  Project.998S/Assets/HanWooJeong/Inventory/ItemClick.png
  Project.998S/Assets/HanWooJeong/ItemOption/PcProfileMask.png
  Project.998S/Assets/HanWooJeong/Prefabs/InventoryPopup.prefab
  Project.998S/Assets/HanWooJeong/Prefabs/ItemPopup.prefab
  Project.998S/Assets/HanWooJeong/Title/ftklogo_horz.png
  Project.998S/Assets/HanWooJeong/WinPopup/ProfielClippingMask.png
  Project.998S/Assets/HanWooJeong/WinPopup/ProfielClippingMask.png.meta
  Project.998S/Assets/HanWooJeong/WinPopup/ProfileMask.png
  Project.998S/Assets/HanWooJeong/WinPopup/ProfileMask.png.meta
Labels: enhancement

#152 [Feature] 다음 라운드로의 턴 구현
  Project.998S/Assets/HanWooJeong/Inventory/GodItemS.png.meta
  Project.998S/Assets/Resources/Prefabs/EnemyActionPopup.prefab
  Project.998S/Assets/Resources/Prefabs/EnemyActionPopup.prefab.meta
  Project.998S/Assets/Resources/Prefabs/PlayerActionPopup.prefab
  Project.998S/Assets/Resources/Sprites/ftklogo_horz.png.meta
  Project.998S/Assets/Scripts/Character/Controller/Default/Controller.cs
  Project.998S/Assets/Scripts/Character/Controller/EnemyController.cs
  Project.998S/Assets/Scripts/Character/Controller/PlayerController.cs
  Project.998S/Assets/Scripts/Data/Util/Define.cs
  Project.998S/Assets/Scripts/Manager/SpawnManager.cs
  Project.998S/Assets/Scripts/Manager/StageManager.cs
  Project.998S/Assets/Scripts/UI/Popup/EnemyActionPopup.cs
  Project.998S/Assets/Scripts/UI/Popup/EnemyActionPopup.cs.meta
  Project.998S/Assets/Scripts/UI/Popup/PlayerActionPopup.cs
  Project.998S/Assets/Scripts/UI/Popup/PlayerActionPopup.cs.meta
  Project.998S/Assets/Scripts/UI/SubItem/PlayerHUDSubItem.cs
Labels: enhancement

#166 [Fix] 몬스터 슬롯 확률 버그 수정
  Project.998S/Assets/Scripts/Character/Controller/EnemyController.cs
  Project.998S/Assets/Scripts/Data/Util/Define.cs
  Project.998S/Assets/Scripts/UI/Popup/EnemyActionPopup.cs
Labels: bug, enhancement
